config/routes.rb
Rails.application.routes.draw do
  resources :catalogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/catalog.rb
class Catalog < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  before_action :set_catalog, only: [:show, :edit, :update, :destroy]

  # GET /catalogs
  # GET /catalogs.json
  def index
    @catalogs = Catalog.all
  end

  # GET /catalogs/1
  # GET /catalogs/1.json
  def show
  end

  # GET /catalogs/new
  def new
    @catalog = Catalog.new
  end

  # GET /catalogs/1/edit
  def edit
  end

  # POST /catalogs
  # POST /catalogs.json
  def create
    @catalog = Catalog.new(catalog_params)

    respond_to do |format|
      if @catalog.save
        format.html { redirect_to @catalog, notice: 'Catalog was successfully created.' }
        format.json { render :show, status: :created, location: @catalog }
      else
        format.html { render :new }
        format.json { render json: @catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catalogs/1
  # PATCH/PUT /catalogs/1.json
  def update
    respond_to do |format|
      if @catalog.update(catalog_params)
        format.html { redirect_to @catalog, notice: 'Catalog was successfully updated.' }
        format.json { render :show, status: :ok, location: @catalog }
      else
        format.html { render :edit }
        format.json { render json: @catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catalogs/1
  # DELETE /catalogs/1.json
  def destroy
    @catalog.destroy
    respond_to do |format|
      format.html { redirect_to catalogs_url, notice: 'Catalog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catalog
      @catalog = Catalog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def catalog_params
      params.require(:catalog).permit(:name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/views/catalogs/_form.html.erb
<%= form_with(model: catalog, local: true, html: { multipart: true } ) do |form| %>
  <% if catalog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(catalog.errors.count, "error") %> prohibited this catalog from being saved:</h2>

      <ul>
      <% catalog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/catalogs/edit.html.erb
<h1>Editing Catalog</h1>

<%= render 'form', catalog: @catalog %>

<%= link_to 'Show', @catalog %> |
<%= link_to 'Back', catalogs_path %>

app/views/catalogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Catalogs</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @catalogs.each do |catalog| %>
      <tr>
        <td><%= image_tag catalog.image.url(:medium) %>
        <td><%= catalog.name %></td>
        <td><%= link_to 'Show', catalog %></td>
        <td><%= link_to 'Edit', edit_catalog_path(catalog) %></td>
        <td><%= link_to 'Destroy', catalog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Catalog', new_catalog_path %>

app/views/catalogs/new.html.erb
<h1>New Catalog</h1>

<%= render 'form', catalog: @catalog %>

<%= link_to 'Back', catalogs_path %>

app/views/catalogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @catalog.name %>
</p>

<p>
	<strong>Image</strong>
	<%= image_tag @catalog.image.url %>
</p>

<%= link_to 'Edit', edit_catalog_path(@catalog) %> |
<%= link_to 'Back', catalogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KaprizBox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>